/*I/*/
/*Growth and Revenue Analysis*/

/*total revenue generated by Olist platform*/
USE olist_ecommerce;
SELECT 
    SUM(price + freight_value) AS total_revenue
        FROM order_items;

/*revenue generated yearly*/
SELECT 
    YEAR(o.order_purchase_timestamp) AS year,
    SUM(oi.price + oi.freight_value) AS revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY YEAR(o.order_purchase_timestamp)
ORDER BY year;

/*revenue generated monthly each year (only delivered product, so the cancelled/returned orders are excluded)*/
SELECT 
    DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
    SUM(oi.price + oi.freight_value) AS revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY month
ORDER BY month;

/*growth percentage month over month*/
SELECT
    month,
    revenue,
    previous_month_revenue,
    ROUND(
        (revenue - previous_month_revenue) 
        / NULLIF(previous_month_revenue, 0) * 100,
        2
    ) AS growth_percentage
FROM (
    SELECT 
        month,
        revenue,
        LAG(revenue) OVER (ORDER BY month) AS previous_month_revenue
    FROM (
        SELECT 
            DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
            SUM(oi.price + oi.freight_value) AS revenue
        FROM orders o
        JOIN order_items oi 
            ON o.order_id = oi.order_id
        GROUP BY DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')
    ) AS monthly_revenue
) AS final_table
ORDER BY month;

/*growth percentage month over month for delivered products only*/
SELECT
    month,
    revenue,
    previous_month_revenue,
    ROUND(
        (revenue - previous_month_revenue) 
        / NULLIF(previous_month_revenue, 0) * 100,
        2
    ) AS growth_percentage
FROM (
    SELECT 
        month,
        revenue,
        LAG(revenue) OVER (ORDER BY month) AS previous_month_revenue
    FROM (
        SELECT 
            DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
            SUM(oi.price + oi.freight_value) AS revenue
        FROM orders o
        JOIN order_items oi 
            ON o.order_id = oi.order_id
        WHERE o.order_status = 'delivered'
        GROUP BY DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')
    ) AS monthly_revenue
) AS final_table
ORDER BY month;

/*month with the highest growth percentage*/
WITH monthly_revenue AS (
    SELECT 
        DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
        SUM(oi.price + oi.freight_value) AS revenue
    FROM orders o
    JOIN order_items oi 
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY month
),
growth_calc AS (
    SELECT 
        month,
        revenue,
        ROUND(
            ((revenue - LAG(revenue) OVER (ORDER BY month)) 
            / LAG(revenue) OVER (ORDER BY month)) * 100, 
        2) AS growth_percentage
    FROM monthly_revenue
)
SELECT *
FROM growth_calc
ORDER BY growth_percentage DESC
LIMIT 1;

/*II/*/
/*Customer Analytics*/
/*Monthly repeated purchase rate from same customer*/
WITH customer_orders AS(
    SELECT DATE_FORMAT(order_purchase_timestamp, '%Y-%m') AS y_month, customer_id, COUNT(order_id) AS total_orders
    FROM orders
    WHERE order_status = 'delivered'
    GROUP BY DATE_FORMAT(order_purchase_timestamp, '%Y-%m'), customer_id
)
SELECT 
    y_month,
    COUNT(CASE WHEN total_orders > 1 Then 1 END) AS repeat_customers,
    COUNT(*) AS total_customers,
    ROUND(COUNT(CASE WHEN total_orders > 1 Then 1 END)/COUNT(*) * 100, 2) AS repeat_purchase_rate
FROM customer_orders
GROUP BY y_month
ORDER BY y_month ASC;

/*All time repeated purchase rate from same customer*/
WITH customer_orders AS (
    SELECT 
        customer_id, 
        COUNT(order_id) AS total_orders
    FROM orders
    WHERE order_status = 'delivered'
    GROUP BY customer_id
)
SELECT
    COUNT(CASE WHEN total_orders > 1 THEN 1 END) AS repeat_customers,
    COUNT(*) AS total_customers,
    ROUND(COUNT(CASE WHEN total_orders > 1 THEN 1 END) * 100.0 / COUNT(*), 2) AS repeat_purchase_rate
FROM customer_orders;

/* This dataset doe not contain repeated customers, as each customer has only one order. Therefore, the repeat purchase rate is 0% for both monthly and all time repeat_purchase_rate.*/