/*I/*/
/*Growth and Revenue Analysis*/

/*total revenue generated by Olist platform*/
USE olist_ecommerce;
SELECT 
    SUM(price + freight_value) AS total_revenue
        FROM order_items;

/*revenue generated yearly*/
SELECT 
    YEAR(o.order_purchase_timestamp) AS year,
    SUM(oi.price + oi.freight_value) AS revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY YEAR(o.order_purchase_timestamp)
ORDER BY year;

/*revenue generated monthly each year (only delivered product, so the cancelled/returned orders are excluded)*/
SELECT 
    DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
    SUM(oi.price + oi.freight_value) AS revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY month
ORDER BY month;

/*growth percentage month over month*/
SELECT
    month,
    revenue,
    previous_month_revenue,
    ROUND(
        (revenue - previous_month_revenue) 
        / NULLIF(previous_month_revenue, 0) * 100,
        2
    ) AS growth_percentage
FROM (
    SELECT 
        month,
        revenue,
        LAG(revenue) OVER (ORDER BY month) AS previous_month_revenue
    FROM (
        SELECT 
            DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
            SUM(oi.price + oi.freight_value) AS revenue
        FROM orders o
        JOIN order_items oi 
            ON o.order_id = oi.order_id
        GROUP BY DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')
    ) AS monthly_revenue
) AS final_table
ORDER BY month;

/*growth percentage month over month for delivered products only*/
SELECT
    month,
    revenue,
    previous_month_revenue,
    ROUND(
        (revenue - previous_month_revenue) 
        / NULLIF(previous_month_revenue, 0) * 100,
        2
    ) AS growth_percentage
FROM (
    SELECT 
        month,
        revenue,
        LAG(revenue) OVER (ORDER BY month) AS previous_month_revenue
    FROM (
        SELECT 
            DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
            SUM(oi.price + oi.freight_value) AS revenue
        FROM orders o
        JOIN order_items oi 
            ON o.order_id = oi.order_id
        WHERE o.order_status = 'delivered'
        GROUP BY DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')
    ) AS monthly_revenue
) AS final_table
ORDER BY month;

/*month with the highest growth percentage*/
WITH monthly_revenue AS (
    SELECT 
        DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
        SUM(oi.price + oi.freight_value) AS revenue
    FROM orders o
    JOIN order_items oi 
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY month
),
growth_calc AS (
    SELECT 
        month,
        revenue,
        ROUND(
            ((revenue - LAG(revenue) OVER (ORDER BY month)) 
            / LAG(revenue) OVER (ORDER BY month)) * 100, 
        2) AS growth_percentage
    FROM monthly_revenue
)
SELECT *
FROM growth_calc
ORDER BY growth_percentage DESC
LIMIT 1;

